-- auto-generated by Cube's CompanionDataParser tool at 2026-07-29 13:42:41

if (LANGUAGE ~= "ES") then return true; end

-- Language-dependent quest-name to quest ID lookup
_CONFLICTING_QUEST_NAME_TO_ID = {
    ["After the Battle"] = 1879335348; -- Deed ID: 1879334733
    ["Aiding the Eastemnet"] = 1879240578; -- Deed ID: 1879248360
    ["Asalto a la guarida de los Espectros del Anillo"] = 1879160626; -- Deed ID: 1879175326
    ["Ataque al alba"] = 1879208421; -- Deed ID: 1879209658
    ["Ataque contra Dannenglor"] = 1879160578; -- Deed ID: 1879173661
    ["Defensa del Poney Pisador"] = 1879162702; -- Deed ID: 1879162646
    ["Defensa en Amon Sûl"] = 1879159798; -- Deed ID: 1879159790
    ["Descubrir al descendiente"] = 1879234348; -- Deed ID: 1879234462
    ["El Agujero Embrujado"] = 1879189266; -- Deed ID: 1879191253
    ["El Camino del Cazador"] = 1879048304; -- Deed ID: 1879052486
    ["El círculo de la desesperación"] = 1879396465; -- Deed ID: 1879085025
    ["El picnic perfecto"] = 1879367046; -- Deed ID: 1879367049
    ["Farms of the Fallows"] = 1879262826; -- Deed ID: 1879265473
    ["Fuera del Norte"] = 1879143335; -- Deed ID: 1879457968
    ["Herramientas del oficio"] = 1879309913; -- Deed ID: 1879277293
    ["Hora de necesidad"] = 1879091387; -- Deed ID: 1879277369
    ["La batalla en la torre"] = 1879160343; -- Deed ID: 1879173664
    ["La comunidad perdida"] = 1879109321; -- Deed ID: 1879110246
    ["La Grieta Helada"] = 1879207159; -- Deed ID: 1879208174
    ["La mejor defensa"] = 1879240242; -- Deed ID: 1879060151
    ["La perdición de Caras Gelebren"] = 1879453538; -- Deed ID: 1879453347
    ["Leave No One Behind"] = 1879393874; -- Deed ID: 1879163179
    ["Little Wonders"] = 1879182762; -- Deed ID: 1879190838
    ["Matador de huargos"] = 1879054427; -- Deed ID: 1879071724, 1879071734, 1879071768, 1879071782, 1879141058, 1879155766, 1879220076
    ["Matadora de huargos"] = 1879054427; -- Deed ID: 1879071724, 1879071734, 1879071768, 1879071782, 1879141058, 1879155766, 1879220076
    ["Ojos del Enemigo"] = 1879304967; -- Deed ID: 1879147022
    ["Problemas en Alforzaburgo"] = 1879156593; -- Deed ID: 1879158107
    ["Protectores de Thangúlhad"] = 1879160668; -- Deed ID: 1879173662
    ["Protectors of the Wilderfolk"] = 1879386531; -- Deed ID: 1879387431
    ["Punto ciego"] = 1879143826; -- Deed ID: 1879277241
    ["Rescate en Nûrz Ghâshu"] = 1879181728; -- Deed ID: 1879182644
    ["Robo y Travesura"] = 1879162680; -- Deed ID: 1879162619
    ["The Battle for Osgiliath"] = 1879326193; -- Deed ID: 1879326392
    ["Tormenta en Methedras"] = 1879224852; -- Deed ID: 1879226092
    ["Un Tiro en la Oscuridad"] = 1879215638; -- Deed ID: 1879052485
};

-- Indexd by Quest ID
_CONFLICTING_QUESTS = {
    -- Gondor / Lejano Anórien / After the Battle
    [1879335348] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Minas Tirith (Después de la batalla) / After the Battle\n    (After the Battle of the Pelennor Fields, Imrahil has summoned you to aid the great city of Minas Tirith.)";
    };

    -- Rhovanion / Rohan Oriental / Aiding the Eastemnet
    [1879240578] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Hytbold / Aiding the Eastemnet (Repetible)\n    (There is much to do to aid the people of the Eastemnet.)";
    };

    -- Skirmish / Escaramuzas / Asalto a la guarida de los Espectros del Anillo
    [1879160626] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Asalto a la guarida de los Espectros del Anillo (Repetible)\n    (Tomar los muros que rodean Dol Guldur dejará las defensas interiores debilitadas y vulnerables)";
        ["ANNOUNCE"] = "Has reclamado el Antro de los Espectros del Anillo. El corazón de Dol Guldur está ahora expuesto";
        ["IS_SKIRMISH"] = true;
    };

    -- Skirmish / Escaramuzas / Ataque al alba
    [1879208421] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Ataque al alba (Repetible)\n    (En lo más profundo de la noche, una partida de exploradores trasgos ha descubierto la ubicación del regugio de montaraces conocido como Esteldín. Los trasgos han huido a Dol Dínen, acabad con ellos antes de que puedan traer refuerzos.)";
        ["ANNOUNCE"] = "Habéis derrotado a Graug y asegurado el conocimiento de la ubicación de Esteldín";
        ["IS_SKIRMISH"] = true;
    };

    -- Skirmish / Escaramuzas / Ataque contra Dannenglor
    [1879160578] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Ataque contra Dannenglor (Repetible)\n    (Varios elfos y exploradores han sido hechos prisioneros por un hechicero en las antiguas ruinas élficas de Dannenglor.)";
        ["ANNOUNCE"] = "El hechicero y la amenaza de Dannenglor han sido derrotados. Audaghaim y la Hueste Dorada están a salvo";
        ["IS_SKIRMISH"] = true;
    };

    -- Skirmish / Escaramuzas / Defensa del Poney Pisador
    [1879162702] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Defensa del Poney Pisador (Repetible)\n    (Las mujeres y los niños de Bree se han atrincherado dentro de la posada del Poney Pisador. Los bandidos y maleantes que tomaron el pueblo quieren castigar a quienes se oponen a ellos.)";
        ["ANNOUNCE"] = "Goilag ha sido derrotado. Bree está a salvo";
        ["IS_SKIRMISH"] = true;
    };

    -- Skirmish / Escaramuzas / Defensa en Amon Sûl
    [1879159798] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Defensa en Amon Sûl (Repetible)\n    (Un enfrentamiento entre los Nazgûl y el mago Gandalf ha atraído a los sirvientes del Rey Brujo a la Cima de los Vientos. Con el fin de derrotar al Cargûl que guía a las fuerzas oscuras hacia las ruinas de Amon Sûl, el montaraz Candaith ha preparado una emboscada.)";
        ["ANNOUNCE"] = "El Cargûl ha sido vencido, y Candaith ha sobrevivido para llevar la noticia a Rivendel";
        ["IS_SKIRMISH"] = true;
    };

    -- Class/Race/Epic / Épica / Descubrir al descendiente
    [1879234348] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Descubrir al descendiente / Descubrir al descendiente\n    (For centuries the Mearas have freely roamed the plains of Rohan, only bowing before the kings and princes of the Rohirrim.)";
    };

    -- Class/Race/Epic / Raza y sociedad / El Agujero Embrujado
    [1879189266] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Fiesta de la cosecha / El Agujero Embrujado (Repetible)\n    (¿Contiene la carta de Bilbo una pista para acceder a la bodega cerrada? Lobelia parece pensar que sí...)";
    };

    -- Class/Race/Epic / Clase / El Camino del Cazador
    [1879048304] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Cazador / El Camino del Cazador\n    (Para un verdadero cazador, la velocidad y la precisión lo son todo. La falta de una trae mala fortuna. La falta de ambas, desastre.)";
    };

    -- Eriador / Angmar / El círculo de la desesperación
    [1879396465] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Imlad Morgul: Minas Morgul / El círculo de la desesperación\n    (After gaining a foothold in Barad Arthir, Prince Faramir himself has arrived to lead the Rangers of Ithilien in securing the Circle of Despair and the Circle of Death.)";
    };

    -- Skirmish / Escaramuzas / El picnic perfecto
    [1879367046] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Feria del Granjero / El picnic perfecto (Repetible)\n    (¡Qué gran día para un picnic!)";
        ["ANNOUNCE"] = "El picnic se ha salvado. ¡La lluvia incluso refrescó un poco el ambiente!";
        ["ISDELAYED"] = true; -- Quest finishes after eating food
        ["IS_SKIRMISH"] = true;
    };

    -- Rhovanion / Tierras feroces / Farms of the Fallows
    [1879262826] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Tierras feroces: Fallows / Farms of the Fallows\n    (The farms in the Fallows were abandoned when Núrzum attacked Forlaw, and it was deemed unsafe to be outside the city walls. Thrymm's Farm is the meeting place for anyone in the outlying farms who are escaping to the safety of Forlaw.)";
    };

    -- Class/Race/Epic / Clase / Fuera del Norte
    [1879143335] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Eregion / Fuera del Norte\n    (Los Angmarim recorren Eregion en busca de cualquier vestigio del pasado que pueda reforzar aún más sus fuerzas. El pequeño grupo de elfos que se encuentra en Echad Mirobel desea conservar las ruinas tal y como están, y te ha pedido que les ayudes en esta misión.)";
    };

    -- Class/Race/Epic / Clase / Herramientas del oficio
    [1879309913] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Gondor occidental: Belfalas / Herramientas del oficio (Repetible)\n    (The corsairs have started packing up and moving the tools used by the craftsmen.)";
    };

    -- Class/Race/Epic / Clase / Hora de necesidad
    [1879091387] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Annúminas / Hora de necesidad (Repetible)\n    (Dannassel te ha dicho que en tiempos de paz se escondieron por la ciudad cierto número de alijos.)";
    };

    -- Skirmish / Escaramuzas / La batalla en la torre
    [1879160343] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / La batalla en la torre (Repetible)\n    (El Enemigo está atrincherado en la Torre de Dol Guldur. Es el momento de golpearles en el corazón.)";
        ["ANNOUNCE"] = "Has conquistado la Armería y recuperado Zigilburk";
        ["IS_SKIRMISH"] = true;
    };

    -- Eriador / Forochel / La comunidad perdida
    [1879109321] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Angmar / La comunidad perdida\n    (Helegdir te ha pedido que le ayudes a velar por la seguridad de un grupo de individuos conocidos como la Comunidad Perdida.)";
    };

    -- Skirmish / Escaramuzas / La Grieta Helada
    [1879207159] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / La Grieta Helada (Repetible)\n    (Angmar intenta usar poderes oscuros para convocar una ventisca que congele Evendim.)";
        ["ANNOUNCE"] = "El plan de Angmar ha sido frustrado. Evendim está a salvo, por ahora.";
        ["IS_SKIRMISH"] = true;
    };

    -- Class/Race/Epic / Clase / La mejor defensa
    [1879240242] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Valle del Entaguas / La mejor defensa\n    (After hearing from both Lord Ingmar and Lady Góda, you brought your support of Góda's plan to Reeve Ingbert.)";
    };

    -- Skirmish / Escaramuzas / La perdición de Caras Gelebren
    [1879453538] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / La perdición de Caras Gelebren (Repetible)\n    (Caras Gelebren, el bastión plateado, fue una vez la capital de Tham Mírdain y la joya de Eregion. Por desgracia, la ruina cayó sobre ella cuando Sauron, buscando hacerse con los Anillos de Poder, reunió sus vastos ejércitos y destruyó toda Eregion.)";
        ["ANNOUNCE"] = "¡El campeón del Enemigo ha sido derrotado!";
        ["ISDELAYED"] = true; -- Quest completion is the first Quest chat item after this announcement, but there is about two minutes of NPC talking in between.
        ["IS_SKIRMISH"] = true;
    };

    -- Instances / Torre de Dol Guldur / Leave No One Behind
    [1879393874] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Imlad Morgul: Círculo de Locura / Leave No One Behind\n    (You have escaped from the Halls of Black Lore, but without Faeron. You must find him and discover if it was indeed Viznak you heard inside.)";
    };

    -- Eriador / Enedwaith / Little Wonders
    [1879182762] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Enedwaith / Little Wonders\n    (You discovered an object which by all appearances belongs to a child, though it does not seem to be Dunlending in nature.)";
    };

    -- Eriador / Angmar / Matador de huargos, Eriador / Montañas Nubladas / Matador de huargos, Eriador / Quebradas del Norte / Matador de huargos, Eriador / Tierras Brunas / Matador de huargos, Eriador / Tierras Solitarias / Matador de huargos, Rhovanion / Bosque Negro Meridional / Matador de huargos, Rhovanion / Moria / Matador de huargos
    [1879054427] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Quebradas del Norte / Matador de huargos\n    (Huargos viles merodean por las Quebradas del Norte, cazando a quienes se oponen a sus amos. Su presencia amenaza la seguridad de Esteldín.)";
    };

    -- Instances / Minas de Moria / Ojos del Enemigo
    [1879304967] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Trollshaws / Ojos del Enemigo (Repetible)\n    (Los hendrevail, a menudo usados como espías por el Enemigo, han empezado a aparecer en las Gargantas del Bruinen.)";
    };

    -- Skirmish / Escaramuzas / Problemas en Alforzaburgo
    [1879156593] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Problemas en Alforzaburgo (Repetible)\n    (Alforzaburgo es la aldea principal de las Tierras de los Tuk y hogar del Thain de la Comarca. Trasgos y semiorcos buscan conquistarla en nombre de Zarquino, el jefe bandido que azota las Tierras de Bree y la Comarca.)";
        ["ANNOUNCE"] = "El semiorco que lideraba el asalto ha caído. Los bandidos y trasgos restantes se dispersan. Los Grandes Smials están a salvo";
        ["IS_SKIRMISH"] = true;
    };

    -- Skirmish / Escaramuzas / Protectores de Thangúlhad
    [1879160668] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Protectores de Thangúlhad (Repetible)\n    (Thangúlhad está siendo asaltada por las fuerzas de Dol Guldur. Quieren recuperarla y eliminar el enclave que la Hueste Dorada ha asegurado.)";
        ["ANNOUNCE"] = "Mazaukal ha sido derrotado. Thangúlhad está a salvo";
        ["IS_SKIRMISH"] = true;
    };

    -- Rhovanion / Valles de Anduin / Protectors of the Wilderfolk
    [1879386531] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Valles del Anduín: protectores de los pueblos salvajes / Protectors of the Wilderfolk\n    (Representatives of the Wilderfolk have gathered in Hultvís in order to work together and protect the Vales of Anduin.)";
    };

    -- Class/Race/Epic / Clase / Punto ciego
    [1879143826] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Cazador / Punto ciego\n    (Brazofero te ha pedido rastrear el camino de un enano desaparecido y traerle cualquier evidencia que encuentres de su paso.)";
    };

    -- Skirmish / Escaramuzas / Rescate en Nûrz Ghâshu
    [1879181728] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Rescate en Nûrz Ghâshu (Repetible)\n    (Golodir se ha aventurado en las profundidades de Nûrz Ghâshu, y su íntimo amigo Corunir está desesperado por salvarlo)";
        ["ANNOUNCE"] = "Erebún ha sido derrotado y Golodir ha sido liberado";
        ["ISDELAYED"] = true; -- Quest finishes after talking with Corunir / Golodir
        ["IS_SKIRMISH"] = true;
    };

    -- Skirmish / Escaramuzas / Robo y Travesura
    [1879162680] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Robo y Travesura (Repetible)\n    (Mientras los Montaraces del Norte estaban distraídos en el Sur, unos bandidos aprovecharon la oportunidad para arrebatar el control de Bree....)";
        ["ANNOUNCE"] = "Has recuperado el Ayuntamiento y liberado el sur de Bree.";
        ["IS_SKIRMISH"] = true;
    };

    -- The War / Osgiliath / The Battle for Osgiliath
    [1879326193] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Osgiliath: Corte de Anárion / The Battle for Osgiliath\n    (Melethon welcomes you to the battle for Osgiliath and orders you to assist him and the other captains in their efforts to retake the city.)";
    };

    -- Skirmish / Escaramuzas / Tormenta en Methedras
    [1879224852] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Escaramuza / Tormenta en Methedras (Repetible)\n    (Has acompañado a los Montaraces Saeradan y Amlan para enfrentarte a la bruja Gwyllion, llamada la Vieja Mujer de la Montaña por los habitantes locales de las Tierras Brunas, en su hogar en la cima del Methedras, una gran montaña que domina el valle de Nan Curunír e Isengard.)";
        ["ANNOUNCE"] = "Gwyllion y Echrud han sido derrotados, eliminando así la amenaza de la Vieja Mujer de Rohan";
        ["ISDELAYED"] = true; -- Quest finishes after talking with Saeradan and receiving reward.
        ["IS_SKIRMISH"] = true;
    };

    -- Class/Race/Epic / Clase / Un Tiro en la Oscuridad
    [1879215638] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Paso de Rohan: Valle del Isen / Un Tiro en la Oscuridad\n    (The Rohirrim forces prepare to launch a pre-emptive strike against the village of Brôntrig in hopes of confounding the Dunlendings' own attack plans.)";
    };

};

