-- auto-generated by Cube's CompanionDataParser tool at 2026-08-04 18:46:06

if (LANGUAGE ~= "DE") then return true; end

-- Language-dependent quest-name to quest ID lookup
_CONFLICTING_QUEST_NAME_TO_ID = {
    ["Am Tor des Geisterbeschwörers"] = 1879160602; -- Deed ID: 1879163850
    ["Angriff bei Morgengrauen"] = 1879208421; -- Deed ID: 1879209658
    ["Ärger in Buckelstadt"] = 1879156593; -- Deed ID: 1879158107
    ["Aus dem Norden"] = 1879143335; -- Deed ID: 1879457968
    ["Beschützer von Thangúlhad"] = 1879160668; -- Deed ID: 1879173662
    ["Beutlins Geburtstag"] = 1879282924; -- Deed ID: 1879283004
    ["Das Gefecht am Amon Sûl"] = 1879159798; -- Deed ID: 1879159790
    ["Das Handwerkszeug"] = 1879309913; -- Deed ID: 1879277293
    ["Das letzte Wort"] = 1879275583; -- Deed ID: 1879060153
    ["Das Licht der Hoffnung"] = 1879054129; -- Deed ID: 1879277281
    ["Das perfekte Picknick"] = 1879367046; -- Deed ID: 1879367049
    ["Das Versteck der Ringgeister"] = 1879160626; -- Deed ID: 1879175326
    ["Der Alte Wald"] = 1879049664; -- Deed ID: 1879071671
    ["Der Kampf im Turm"] = 1879160343; -- Deed ID: 1879173664
    ["Der Kampf um die Einundzwanzigste Halle"] = 1879198363; -- Deed ID: 1879202439
    ["Der Kreis der Verzweiflung"] = 1879396465; -- Deed ID: 1879085025
    ["Der Schlag gegen Dannenglor"] = 1879160578; -- Deed ID: 1879173661
    ["Der Sturm auf Methedras"] = 1879224852; -- Deed ID: 1879226092
    ["Der Untergang von Caras Gelebren"] = 1879453538; -- Deed ID: 1879453347
    ["Die Augen des Feindes"] = 1879304967; -- Deed ID: 1879147022
    ["Die Belagerung von Gondamon"] = 1879156590; -- Deed ID: 1879157752
    ["Die Beschützer des Wilden Volkes"] = 1879386531; -- Deed ID: 1879387431
    ["Die beste Verteidigung"] = 1879240242; -- Deed ID: 1879060151
    ["Die Bruinenfurt"] = 1879158958; -- Deed ID: 1879159240
    ["Die Eisige Kluft"] = 1879207159; -- Deed ID: 1879208174
    ["Die Entdeckung des Nachfahren"] = 1879234348; -- Deed ID: 1879234462
    ["Die Erkundung von Hatokáli"] = 1879524968; -- Deed ID: 1879525229
    ["Die heimgesuchte Erdhöhle"] = 1879189266; -- Deed ID: 1879191253
    ["Die Lodernden Tiefen"] = 1879143364; -- Deed ID: 1879141031
    ["Die Schlacht um Osgiliath"] = 1879326193; -- Deed ID: 1879326392
    ["Die Stärke des Feindes"] = 1879314810; -- Deed ID: 1879147020
    ["Die Verlorenen Gefährten"] = 1879109321; -- Deed ID: 1879110246
    ["Die Verteidigung des 'Tänzelnden Ponys'"] = 1879162702; -- Deed ID: 1879162646
    ["Die Waffen des Feindes"] = 1879048627; -- Deed ID: 1879147018
    ["Dieberei und Unheil"] = 1879162680; -- Deed ID: 1879162619
    ["Ein Schuss ins Blaue"] = 1879215638; -- Deed ID: 1879052485
    ["Eisenmagen"] = 1879143729; -- Deed ID: 1879485104
    ["Fleißiges Bienchen"] = 1879414262; -- Deed ID: 1879197821
    ["Große Verzweiflung"] = 1879091387; -- Deed ID: 1879277369
    ["Hilfe für Ost-Emnet"] = 1879240578; -- Deed ID: 1879248360
    ["Hin und wieder zurück"] = 1879087139; -- Deed ID: 1879381843
    ["Höfe der Brachen"] = 1879262826; -- Deed ID: 1879265473
    ["Kleine Wunder"] = 1879182762; -- Deed ID: 1879190838
    ["Lasst keinen zurück"] = 1879393874; -- Deed ID: 1879163179
    ["Nach der Schlacht"] = 1879335348; -- Deed ID: 1879334733
    ["Rettung in Nûrz Ghâshu"] = 1879181728; -- Deed ID: 1879182644
    ["Rudelführer"] = 1879205149; -- Deed ID: 1879163177
    ["Salz in die Wunde"] = 1879143831; -- Deed ID: 1879277438
    ["Schmuck aus Evendim"] = 1879202378; -- Deed ID: 1879303261
    ["Silberne Zunge"] = 1879243055; -- Deed ID: 1879277337
    ["Warg-Bezwinger"] = 1879054427; -- Deed ID: 1879071724, 1879071734, 1879071768, 1879071782, 1879141058, 1879155766, 1879220076
    ["Warg-Bezwingerin"] = 1879054427; -- Deed ID: 1879071724, 1879071734, 1879071768, 1879071782, 1879141058, 1879155766, 1879220076
};

-- Indexd by Quest ID
_CONFLICTING_QUESTS = {
    -- Scharmützel / Scharmützel-Instanzen / Am Tor des Geisterbeschwörers
    [1879160602] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Am Tor des Geisterbeschwörers (Wiederholbar)\n    (Das Tor des Geisterbeschwörers kennzeichnet den Eingang zum Herzen der äußeren Befestigungen Dol Guldurs. Bevor ein Angriff auf die Festung möglich wird, muss zuerst das Tor fallen.)";
        ["ANNOUNCE"] = "Das Tor des Geisterbeschwörers ist gefallen. Nun kann das Herz Dol Guldurs angegriffen werden.";
        ["IS_SKIRMISH"] = true;
    };

    -- Scharmützel / Scharmützel-Instanzen / Angriff bei Morgengrauen
    [1879208421] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Angriff bei Morgengrauen (Wiederholbar)\n    (Spätabends hat eine Gruppe Bilwiss-Kundschafter die Position der Waldläufer-Zuflucht Esteldín ausgemacht. Die Bilwisse sind nach Dol Dínen geflohen. Dort müsst Ihr sie stellen und vernichten, bevor sie Verstärkung holen können.)";
        ["ANNOUNCE"] = "Besiegt Graug und sichert die Informationen über Esteldíns Lage";
        ["IS_SKIRMISH"] = true;
    };

    -- Scharmützel / Scharmützel-Instanzen / Ärger in Buckelstadt
    [1879156593] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Ärger in Buckelstadt (Wiederholbar)\n    (Buckelstadt ist die wichtigste Siedlung von Tukland und Sitz des Thains des Auenlandes. Bilwisse und Halborks wollen die Stadt im Namen von Scharrer einnehmen, dem Räuber-Hauptmann, der Bree und dem Auenland viel Ärger bereitet.)";
        ["ANNOUNCE"] = "Der Halbork, der den Angriff anführte, ist gefallen. Die verbleibenden Räuber und Bilwisse zerstreuen sich. Die Groß-Smials sind sicher.";
        ["IS_SKIRMISH"] = true;
    };

    -- Klasse, Rasse, Epos / Klasse / Aus dem Norden
    [1879143335] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Eregion / Aus dem Norden\n    (Angmarim streifen in Eregion umher und suchen Überreste der Vergangenheit, die ihre Truppen noch weiter stärken könnten. Die kleine Gruppe Elben in Echad Mirobel möchte die Ruinen so erhalten, wie sie sind, und hat Euch gebeten, sie bei dieser Aufgabe zu unterstützen.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Beschützer von Thangúlhad
    [1879160668] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Beschützer von Thangúlhad (Wiederholbar)\n    (Thangúlhad wird von den Streitkräften Dol Guldurs angegriffen. Sie möchten es zurückerobern und die Basis des Goldenen Heeres zerstören.)";
        ["ANNOUNCE"] = "Mazaukal wurde besiegt. Thangúlhad ist sicher.";
        ["IS_SKIRMISH"] = true;
    };

    -- Klasse, Rasse, Epos / Volk & Soziales / Beutlins Geburtstag
    [1879282924] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Fest / Beutlins Geburtstag\n    (Frodo Beutlin sucht nach einem Abenteurer, der bei einer Geburtstagsüberraschung für seinen Onkel Bilbo hilft! Reist nach Bruchtal und erfahrt, wie Ihr dort helfen könnt.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Das Gefecht am Amon Sûl
    [1879159798] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Das Gefecht am Amon Sûl (Wiederholbar)\n    (Nach einer Auseinandersetzung zwischen den Nazgûl und dem Zauberer Gandalf dem Grauen wurden Diener des Hexenkönigs zur Wetterspitze gelockt. Der Waldläufer Candaith hat eine Falle aufgestellt, um den Cargûl zu besiegen, der die dunklen Streitkräfte zu den Ruinen auf dem Amon Sûl führt.)";
        ["ANNOUNCE"] = "Der Cargûl wurde besiegt und Candaith hat überlebt, um in Bruchtal Bericht zu erstatten.";
        ["IS_SKIRMISH"] = true;
    };

    -- Klasse, Rasse, Epos / Klasse / Das Handwerkszeug
    [1879309913] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "West-Gondor: Belfalas / Das Handwerkszeug (Wiederholbar)\n    (Die Korsaren haben damit begonnen, die Werkzeuge der Handwerker zu verstauen und fortzuschaffen.)";
    };

    -- Klasse, Rasse, Epos / Klasse / Das letzte Wort
    [1879275583] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Ostfold / Das letzte Wort\n    (Nachdem Ihr den Hof in der Folde vor der möglichen Gefahr gewarnt hattet, fiel ein Ork-Stoßtrupp über den Hof her.)";
    };

    -- Klasse, Rasse, Epos / Klasse / Das Licht der Hoffnung
    [1879054129] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Angmar / Das Licht der Hoffnung\n    (Búdan hat Euch in die Stadt Donnvail geschickt, um dort mit den Trév Gállorg zu sprechen, die sich vielleicht gegen die Angmarim auflehnen werden.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Das perfekte Picknick
    [1879367046] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Bauernfest / Das perfekte Picknick (Wiederholbar)\n    (Was für ein toller Tag für ein Picknick!)";
        ["ANNOUNCE"] = "Das Picknick ist gerettet. Der Regen hat sogar für eine angenehme Abkühlung gesorgt!";
        ["ISDELAYED"] = true; -- Quest finishes after eating food
        ["IS_SKIRMISH"] = true;
    };

    -- Scharmützel / Scharmützel-Instanzen / Das Versteck der Ringgeister
    [1879160626] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Das Versteck der Ringgeister (Wiederholbar)\n    (Durch die Eroberung der Burghöfe Dol Guldurs wird die innere Verteidigung schwach und verwundbar.)";
        ["ANNOUNCE"] = "Ihr habt das Versteck der Ringgeister erobert. Das Herz von Dol Guldur liegt nun offen.";
        ["IS_SKIRMISH"] = true;
    };

    -- Eriador / Breeland / Der Alte Wald
    [1879049664] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Breeland / Der Alte Wald\n    (Celandine Brandybock hat nach Bauer Maggots Aufzeichnung über den Alten Wald gefragt, aber sie hat sie noch nicht erhalten. Sie macht sich Sorgen, dass etwas passiert sein könnte.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Der Kampf im Turm
    [1879160343] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Der Kampf im Turm (Wiederholbar)\n    (Der Feind hat sich im Turm von Dol Guldur verschanzt. Es ist an der Zeit, ihn mitten ins Herz zu treffen und zu vernichten.)";
        ["ANNOUNCE"] = "Ihr habt die Waffenkammer erobert und Zigilburk zurückgeholt.";
        ["IS_SKIRMISH"] = true;
    };

    -- Scharmützel / Scharmützel-Instanzen / Der Kampf um die Einundzwanzigste Halle
    [1879198363] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Der Kampf um die Einundzwanzigste Halle (Wiederholbar)\n    (Ihr seid zur Einundzwanzigsten Halle geeilt, um bei ihrer Verteidigung zu helfen. Folgt Wílis Anweisungen und helft den Zwergen, Moria zu verteidigen!)";
        ["IS_SKIRMISH"] = true;
    };

    -- Eriador / Angmar / Der Kreis der Verzweiflung
    [1879396465] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Imlad Morgul: Minas Morgul / Der Kreis der Verzweiflung\n    (Nachdem sie in Barad Arthir Fuß gefasst hatten, kam Prinz Faramir persönlich und führte die Waldläufer von Ithilien an, um den Ring der Verzweiflung und den Ring des Todes zu sichern.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Der Schlag gegen Dannenglor
    [1879160578] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Der Schlag gegen Dannenglor (Wiederholbar)\n    (Mehrere Elben und Waldläufer wurden von einem Zauberer in den uralten Elbenruinen von Dannenglor gefangen genommen.)";
        ["ANNOUNCE"] = "Der Zauberer und die Bedrohung von Dannenglor wurden besiegt. Audaghaim und das Goldene Heer sind sicher.";
        ["IS_SKIRMISH"] = true;
    };

    -- Scharmützel / Scharmützel-Instanzen / Der Sturm auf Methedras
    [1879224852] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Der Sturm auf Methedras (Wiederholbar)\n    (Ihr seid mit den Waldläufern Saeradan und Amlan aufgebrochen, um der Hexe Gwyllion die Stirn zu bieten, die von den Dunländern die alte Frau des Berges genannt wird. Sie hält sich in ihrer Behausung auf der Spitze des Methedras auf, einem großen Berg, von dem aus man auf das Tal Nan Curunír und auf Isengart hinabschaut.)";
        ["ANNOUNCE"] = "Gwyllion und Echrud sind bezwungen, und die alte Frau stellt keine Bedrohung für Rohan mehr da.";
        ["ISDELAYED"] = true; -- Quest finishes after talking with Saeradan and receiving reward.
        ["IS_SKIRMISH"] = true;
    };

    -- Scharmützel / Scharmützel-Instanzen / Der Untergang von Caras Gelebren
    [1879453538] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Der Untergang von Caras Gelebren (Wiederholbar)\n    (Caras Gelebren, die Silberne Bastion, war einst die Hauptstadt von Tham Mírdain und das Juwel von Eregion. Leider wurde es vor langer Zeit zerstört, als Sauron auf der Suche nach den Ringen der Macht seine gewaltigen Armeen versammelte und ganz Eregion verwüstete.)";
        ["ANNOUNCE"] = "Der Waffenmeister des Feindes wurde bezwungen!";
        ["ISDELAYED"] = true; -- Quest completion is the first Quest chat item after this announcement, but there is about two minutes of NPC talking in between.
        ["IS_SKIRMISH"] = true;
    };

    -- Instanzen / Minen von Moria / Die Augen des Feindes
    [1879304967] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Trollhöhen / Die Augen des Feindes (Wiederholbar)\n    (Hendrevail werden vom Feind oft als Spione eingesetzt und werden in den Bruinen-Schluchten immer häufiger beobachtet.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Die Belagerung von Gondamon
    [1879156590] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Die Belagerung von Gondamon (Wiederholbar)\n    (Gondamon ist eine der mächtigsten Festungen der Langbärte in den Blauen Bergen. Die Grimmhands und ihre Bilwiss-Verbündeten wollen die Festung erobern und für sich selbst beanspruchen.)";
        ["IS_SKIRMISH"] = true;
    };

    -- Rhovanion / Täler des Anduin / Die Beschützer des Wilden Volkes
    [1879386531] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Täler des Anduin: Die Beschützer des Wilden Volkes / Die Beschützer des Wilden Volkes\n    (In Hultvís haben sich Vertreter des Wilden Volks versammelt, um zusammenzuarbeiten und die Täler des Anduin zu schützen.)";
    };

    -- Klasse, Rasse, Epos / Klasse / Die beste Verteidigung
    [1879240242] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Entwasser-Tal / Die beste Verteidigung\n    (Nachdem Ihr beide, Herrn Ingmar und Herrin Góda gehört habt, brachtet Ihr Eure Unterstützung für Gódas Plan vor den Greve Ingbert.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Die Bruinenfurt
    [1879158958] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Die Bruinenfurt (Wiederholbar)\n    (Die Bruinenfurt ist das letzte Bollwerk, das in das verborgene Bruchtal führt. Orks im Dienste Angmars belagern die Furt, um die Verteidigungslinien vom Imladris zu durchbrechen.)";
        ["IS_SKIRMISH"] = true;
    };

    -- Scharmützel / Scharmützel-Instanzen / Die Eisige Kluft
    [1879207159] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Die Eisige Kluft (Wiederholbar)\n    (Angmar versucht, mit finsteren Mächten einen Schneesturm herbeizurufen und Evendim einzufrieren.)";
        ["ANNOUNCE"] = "Angmars Plan wurde durchkreuzt. Evendim ist erst einmal in Sicherheit.";
        ["IS_SKIRMISH"] = true;
    };

    -- Klasse, Rasse, Epos / Epos / Die Entdeckung des Nachfahren
    [1879234348] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Die Entdeckung des Nachfahren / Die Entdeckung des Nachfahren\n    (Jahrhunderte lang streiften die Meoras frei über die Ebenen ganz Rohans und verbeugten sich nur vor den Königen und Prinzen der Rohirrim.)";
    };

    -- Haradwaith / Mûr Ghala / Die Erkundung von Hatokáli
    [1879524968] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Mûr Ghala: Pahar Hatokáli / Die Erkundung von Hatokáli\n    (Razâl war wieder auf Erkundung. Dieses Mal, um Bârshuds neues Lager und ein geeignetes Feldlager für Mizâdi zu finden. Er bittet um Eure Hilfe bei der Suche.)";
    };

    -- Klasse, Rasse, Epos / Volk & Soziales / Die heimgesuchte Erdhöhle
    [1879189266] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Erntefest / Die heimgesuchte Erdhöhle (Wiederholbar)\n    (Ob Bilbos Brief einen Hinweis enthält, wie man Zugang zum versperrten Keller erhalten kann? Lobelia scheint dies zu denken ...)";
    };

    -- Rhovanion / Moria / Die Lodernden Tiefen
    [1879143364] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Moria / Die Lodernden Tiefen\n    (In den Tiefen der Hallen von Moria flackert Feuer aus öligen Lachen. Hier hausen die Ghâsh-hai. Ein Teil von ihnen ist mit Mazog, dem Herrscher von Moria, verbunden und zur Großen Treppe gekommen, um ihrem Anführer zu huldigen.)";
    };

    -- Der Krieg / Osgiliath / Die Schlacht um Osgiliath
    [1879326193] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Osgiliath: Hof von Anárion / Die Schlacht um Osgiliath\n    (Melethon heißt Euch zur Schlacht um Osgiliath willkommen und befiehlt Euch, ihm und den anderen Hauptmännern bei ihrem Vorhaben zu helfen, die Stadt zurückzuerobern.)";
    };

    -- Instanzen / Minen von Moria / Die Stärke des Feindes
    [1879314810] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "West-Gondor: Tarlangs Krone / Die Stärke des Feindes\n    (Harnion möchte mehr über die Stärke der Korsaren in Tarlangs Krone erfahren, bevor es zum Kampf kommt.)";
    };

    -- Eriador / Forochel / Die Verlorenen Gefährten
    [1879109321] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Angmar / Die Verlorenen Gefährten\n    (Helegdir hat Euch gebeten, dabei zu helfen, die Sicherheit einer Gruppe von Personen zu gewährleisten, die man die Verlorenen Gefährten nennt.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Die Verteidigung des 'Tänzelnden Ponys'
    [1879162702] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Die Verteidigung des 'Tänzelnden Ponys' (Wiederholbar)\n    (Die Frauen und Kinder Brees haben sich im Gasthaus 'Zum Tänzelnden Pony' verbarrikadiert. Die Räuber und Raufbolde, welche die Stadt eingenommen haben, wollen jene bestrafen, die sich gegen sie stellen.)";
        ["ANNOUNCE"] = "Goilag wurde besiegt. Bree ist wieder in Sicherheit.";
        ["IS_SKIRMISH"] = true;
    };

    -- Instanzen / Minen von Moria / Die Waffen des Feindes
    [1879048627] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Urugarth / Die Waffen des Feindes\n    (Der Widerstand bei Gath Forthnír braucht Ausrüstung, wenn er sich gegen Carn Dûm halten soll.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Dieberei und Unheil
    [1879162680] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Dieberei und Unheil (Wiederholbar)\n    (Während die Waldläufer des Nordens im Süden beschäftigt waren, haben Räuber und Rüpel die Gelegenheit ergriffen, die Kontrolle über Breeland an sich zu reißen....)";
        ["ANNOUNCE"] = "Ihr habt das Rathaus zurückerobert und den Süden von Bree befreit.";
        ["IS_SKIRMISH"] = true;
    };

    -- Klasse, Rasse, Epos / Klasse / Ein Schuss ins Blaue
    [1879215638] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Pforte von Rohan: Isental / Ein Schuss ins Blaue\n    (Die Rohirrim-Truppen bereiten in der Hoffnung, die Angriffspläne der Dunländer zu vereiteln, einen Präventivschlag gegen das Dorf Brôntrig vor.)";
    };

    -- Klasse, Rasse, Epos / Ruf / Eisenmagen
    [1879143729] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Moria / Eisenmagen\n    (Skûmfíl ist lediglich eine Müllhalde, ein Ort, an dem die gefallenen Orks von Moria entsorgt werden, wenn sie zu verwesen beginnen. Dort haben sich zwei Feinde eingefunden, die die Leichen zu ihrem ganz eigenen Zweck benutzen wollen. Die Kergrim und andere Aasfresser nutzen sie als Nahrungsquelle und die Insekten als Ablageort für ihre Eier, aus denen zukünftige Generationen schlüpfen werden.)";
    };

    -- Klasse, Rasse, Epos / Ruf / Fleißiges Bienchen
    [1879414262] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Frühlingsfest / Fleißiges Bienchen (Wiederholbar)\n    (Es ist Zeit, die Wiesen zu bestäuben!)";
        ["IS_SKIRMISH"] = true;
    };

    -- Klasse, Rasse, Epos / Klasse / Große Verzweiflung
    [1879091387] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Annúminas / Große Verzweiflung (Wiederholbar)\n    (Dannassel hat Euch von einigen Vorratslagern erzählt, die in der Stadt in Friedenszeiten versteckt angelegt wurden.)";
    };

    -- Rhovanion / Ost-Rohan / Hilfe für Ost-Emnet
    [1879240578] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Hytbold / Hilfe für Ost-Emnet (Wiederholbar)\n    (Es gibt eine Menge zu tun, um dem Volk von Ost-Emnet zu helfen.)";
    };

    -- Klasse, Rasse, Epos / Volk & Soziales / Hin und wieder zurück
    [1879087139] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Evendim / Hin und wieder zurück\n    (Der Waldläufer Culang hat von einem großen Schatz erfahren, der vor langer Zeit von einem Dúnedain-Landbesitzer vergraben wurde und den er nun bergen möchte, ehe er Grabräubern in die Hände fällt.)";
    };

    -- Rhovanion / Wildermark / Höfe der Brachen
    [1879262826] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Wildermark: Die Brachen / Höfe der Brachen\n    (Die Höfe in den Brachen wurden aufgegeben, als Núrzum Forlach attackierte und es zu gefährlich war, sich außerhalb der Stadtmauern aufzuhalten. Auf ihrer Flucht ins sicherere Forlach war Thrymms Hof der Sammelpunkt für die Bauern der weiter entfernten Höfe, die entkommen konnten.)";
    };

    -- Eriador / Enedwaith / Kleine Wunder
    [1879182762] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Enedwaith / Kleine Wunder\n    (Ihr habt einen Gegenstand entdeckt, der allem Anschein nach einem Kind gehört, obwohl er nicht von Dunländern gefertigt scheint.)";
    };

    -- Instanzen / Turm von Dol Guldur / Lasst keinen zurück
    [1879393874] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Imlad Morgul: Ring des Wahnsinns / Lasst keinen zurück\n    (Ihr seid aus den Hallen des Dunklen Wissens entkommen, aber ohne Faeron. Ihr müsst ihn finden und herausfinden, ob es wirklich Viznak war, den ihr in den Hallen gehört habt.)";
    };

    -- Gondor / Fernes Anórien / Nach der Schlacht
    [1879335348] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Minas Tirith (schlachtgezeichnet) / Nach der Schlacht\n    (Nach der Schlacht auf dem Pelennor hat Euch Imrahil gebeten, der großen Stadt Minas Tirith beizustehen.)";
    };

    -- Scharmützel / Scharmützel-Instanzen / Rettung in Nûrz Ghâshu
    [1879181728] = {
        ["ISREPEATABLE"] = true;
        ["QUESTNAME"] = "Scharmützel / Rettung in Nûrz Ghâshu (Wiederholbar)\n    (Golodir hat sich tief ins Innere von Nûrz Gâshu begeben und sein guter Freund Corunir drängt auf seine Rettung.)";
        ["ANNOUNCE"] = "Erebún wurde besiegt und Golodir wurde befreit";
        ["ISDELAYED"] = true; -- Quest finishes after talking with Corunir / Golodir
        ["IS_SKIRMISH"] = true;
    };

    -- Instanzen / Turm von Dol Guldur / Rudelführer
    [1879205149] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Isengart: Nan Curunír / Rudelführer\n    (Das Leittier der Isen-Warge, eine Kreatur namens Malmschlund, führt seine Gefährten bei ihren nächtlichen Raubzügen an. Sein Tod würde einen Kampf um seine Nachfolge auslösen, der noch viele Opfer fordern könnte, bis sich ein neues Leittier durchgesetzt hat.)";
    };

    -- Klasse, Rasse, Epos / Klasse / Salz in die Wunde
    [1879143831] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Wächter / Salz in die Wunde\n    (Dithrik hat Euch gebeten, die Drüsen der Kriecher zu sammeln, die im gesamten Wasserwerk zu finden sind.)";
    };

    -- Eriador / Evendim / Schmuck aus Evendim
    [1879202378] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Evendim / Schmuck aus Evendim\n    (Beim Durchwühlen der Dünen haben die Kriecher wohl noch weitere uralte Schmuckstücke verschluckt.)";
    };

    -- Klasse, Rasse, Epos / Klasse / Silberne Zunge
    [1879243055] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Die Norhofen / Silberne Zunge\n    (Ordwacer verursacht wegen einer nicht gelieferten Bestellung bei Trumsele, dem Silberschmied der Stadt des Waldmeisters, Aufruhr bei der Stadtwache.)";
    };

    -- Eriador / Angmar / Warg-Bezwinger, Eriador / Dunland / Warg-Bezwinger, Eriador / Einsame Lande / Warg-Bezwinger, Eriador / Nebelgebirge / Warg-Bezwinger, Eriador / Nordhöhen / Warg-Bezwinger, Rhovanion / Moria / Warg-Bezwinger, Rhovanion / Süd-Düsterwald / Warg-Bezwinger
    [1879054427] = {
        ["ISREPEATABLE"] = false;
        ["QUESTNAME"] = "Nordhöhen / Warg-Bezwinger\n    (Widerliche Warge streifen durch die Nordhöhen und machen Jagd auf alle, die sich ihren Herren entgegenstellen. Ihre Anwesenheit bedroht Esteldíns Sicherheit.)";
    };

};

