MOUNT_LARGE = "large";
MOUNT_SMALL = "small";

_RACE_TO_MOUNT_SIZE_LOOKUP = {
    [0] = MOUNT_LARGE; -- Undefined
   [23] = MOUNT_LARGE; -- Man
   [65] = MOUNT_LARGE; -- Elf
   [73] = MOUNT_SMALL; -- Dwarf
   [81] = MOUNT_SMALL; -- Hobbit
  [114] = MOUNT_LARGE; -- Beorning
  [117] = MOUNT_LARGE; -- High Elf
  [120] = MOUNT_SMALL; -- Stout-axe
  [125] = MOUNT_SMALL; -- River Hobbit
};



SKIRMISH = 1;
SKIRMISH_INSTANCES = 1;
SKIRMISH_LIEUTENANT = 2;

INSTANCES = 2;
I_SHADOWS_OF_ANGMAR = 1;
I_MINES_OF_MORIA = 2;
I_SCOURGE_OF_KHAZAD_DUM = 3;
I_TOWER_OF_DOL_GULDUR = 4;
I_IN_THEIR_ABSENCE = 5;
I_RISE_OF_ISENGARD = 6;
I_THE_ROAD_TO_EREBOR = 7;
I_ASHES_OF_OSGILIATH = 8;
I_THE_BATTLE_OF_PELENNOR = 9;
I_THE_PLATEAU_OF_GORGOROTH = 10;
I_THE_GREY_MOUNTAINS = 11;
I_MINAS_MORGUL = 12;
I_THE_WAR_OF_THREE_PEAKS = 13;
I_THE_MOUNTAIN_HOLD = 14;
I_RETURN_TO_CARN_DUM = 15;
I_CORSAIRS_OF_UMBAR = 16;

HOBBIES = 3;
H_FISHING = 1;

THE_WAR = 4;
W_COMMON = 1;
W_ETTENMOORS = 2;
W_OSGILIATH = 3;

CLASS_RACE_EPIC = 5;
CRE_CLASS = 1;
CRE_RACE_SOCIAL = 2;
CRE_EPIC = 3;
CRE_REPUTATION = 4;
CRE_ALLEGIANCES = 5;

ERIADOR = 6;
E_BREE_LAND = 1;
E_SHIRE = 2;
E_ERED_LUIN = 3;
E_SWANFLEET_CARDOLAN = 4;
E_LONE_LANDS = 5;
E_NORTH_DOWNS = 6;
E_TROLLSHAWS = 7;
E_MISTY_MOUNTAINS = 8;
E_EVENDIM = 9;
E_ANGMAR = 10;
E_FOROCHEL = 11;
E_EREGION = 12;
E_ENEDWAITH = 13;
E_DUNLAND = 14;

RHOVANION = 7;
R_LOTHLORIEN = 1;
R_MORIA = 2;
R_SOUTHERN_MIRKWOOD = 3;
R_GREAT_RIVER = 4;
R_EASTERN_ROHAN = 5;
R_WILDERMORE = 6;
R_WESTERN_ROHAN = 7;
R_STRONGHOLDS_OF_THE_NORTH = 8;
R_THE_DWARF_HOLDS = 9;
R_VALES_OF_ANDUIN = 10;
R_WELLS_OF_LANGFLOOD = 11;
R_ELDERSLADE = 12;
R_BLOOD_OF_AZOG = 13;
R_GUNDABAD = 14;

GONDOR = 8;
G_WESTERN_GONDOR = 1;
G_CENTRAL_GONDOR = 2;
G_EASTERN_GONDOR = 3;
G_OLD_ANORIEN = 4;
G_FAR_ANORIEN = 5;
G_MARCH_OF_THE_KING = 6;
G_THE_WASTES = 7;
G_EASTERN_KINGS_GONDOR = 8;
G_WESTERN_KINGS_GONDOR = 9;
G_OUTER_GONDOR = 10;

MORDOR = 9;
M_GORGOROTH = 1;
M_IMLAD_MORGUL = 2;

HARADWAITH = 10;
H_THE_SHIELD_ISLES = 1;
H_CAPE_OF_UMBAR = 2;
H_UMBAR_BAHARBEL = 3;

_REGION_DEED_START = ERIADOR;
_REGION_DEED_STOP = HARADWAITH;
